# META
META_SYSTEM_USER_TOKEN="..."
META_AD_ACCOUNT_ID="..."
META_BUSINESS_ID="..."
META_PAGE_ID="..."
META_PIXEL_ID="..."
META_IG_ACTOR_ID="..."

# GOOGLE / YOUTUBE
GOOGLE_DEVELOPER_TOKEN="..."
GOOGLE_CLIENT_ID="..."
GOOGLE_CLIENT_SECRET="..."
GOOGLE_REFRESH_TOKEN="..."

# TIKTOK
TIKTOK_ACCESS_TOKEN="..."
TIKTOK_ADVERTISER_ID="..."

# EMAIL
EMAIL_SENDER="you@domain.com"
EMAIL_API_KEY="..."

# APP
MIN_MONTHLY_BUDGET=5000